function createfigure(termografia)
%CREATEFIGURE1(termografia)
%  ZDATA1:  surface zdata
%  Auto-generated by MATLAB on 20-Mar-2020 17:05:51
% Create axes
axes1 = axes('Units','Centimeters','Parent',figure);
hold(axes1,'on');

% Create surf
surf(termografia,'Parent',axes1,'EdgeColor','none');

view(axes1,[-180 90]);

% Attivare o disattivare griglia
grid(axes1,'on');

% Create colorbar
c=colorbar(axes1);
%cLim=[Tot_AVG1-1 Tot_AVG1+1];
%c.Ticks=[10 11 12 13 14 15 16 17 18];
%c.TickLabels={'10\circ','11\circ','12\circ','13\circ','14\circ','15\circ','16\circ','17\circ','18\circ'};
c.Label.String='°C';



