function createfigure2(termografia)
%CREATEFIGURE1(termografia)
%  ZDATA1:  surface zdata
%  Auto-generated by MATLAB on 20-Mar-2020 17:05:51
% Create axes
axes1 = axes('Units','Centimeters','Parent',figure);
hold(axes1,'on');

% Create surf
surf(termografia,'Parent',axes1,'EdgeColor','none');

view(axes1,[-180 90]);

% Attivare o disattivare griglia
grid(axes1,'on');




